# -*- coding: utf-8 -*-
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
OUT_DIR = Path('chapter1_figures')
OUT_DIR.mkdir(exist_ok=True)
DATA_PATH = Path('diamonds.csv')
if DATA_PATH.exists():
    df = pd.read_csv(DATA_PATH)
else:
    from plotnine.data import diamonds as builtin_diamonds
    df = builtin_diamonds.copy()
df = df.loc[:, ~df.columns.str.contains('^Unnamed', case=False, regex=True)]
for col in ['cut', 'color', 'clarity']:
    if col in df.columns:
        df[col] = df[col].astype('category')
numeric_cols = ['carat', 'depth', 'table', 'price', 'x', 'y', 'z']
cat_cols = ['cut', 'color', 'clarity']
sns.set_theme(style='whitegrid', font_scale=0.95)
plt.rcParams['font.family'] = 'DejaVu Sans'
fig, axes = plt.subplots(3, 3, figsize=(12, 10))
axes = axes.ravel()
for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=40, alpha=0.8, edgecolor='black')
    axes[i].axvline(df[col].mean(), linestyle='--', linewidth=1.5, label=f'Среднее: {df[col].mean():.2f}')
    axes[i].axvline(df[col].median(), linestyle=':', linewidth=1.5, label=f'Медиана: {df[col].median():.2f}')
    axes[i].set_title(col)
    axes[i].set_xlabel('Значение')
    axes[i].set_ylabel('Частота')
    axes[i].legend(fontsize=8)
for j in range(len(numeric_cols), len(axes)):
    axes[j].axis('off')
fig.suptitle('Распределение числовых признаков датасета Diamonds Prices', fontsize=14)
fig.tight_layout(rect=[0, 0, 1, 0.97])
fig.savefig(OUT_DIR / 'fig01_numeric_histograms.png', dpi=220, bbox_inches='tight')
plt.close(fig)
sample = df.sample(n=5000, random_state=42)
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
sns.scatterplot(data=sample, x='carat', y='price', hue='cut', alpha=0.45, s=16, ax=axes[0])
axes[0].set_title('Цена от массы (carat) по качеству огранки')
axes[0].set_xlabel('carat')
axes[0].set_ylabel('price, USD')
axes[0].legend(fontsize=7, title='cut')
sns.scatterplot(data=sample, x='x', y='price', hue='clarity', alpha=0.45, s=16, ax=axes[1])
axes[1].set_title('Цена от длины x по чистоте')
axes[1].set_xlabel('x, мм')
axes[1].set_ylabel('price, USD')
axes[1].legend(fontsize=7, title='clarity')
sns.boxplot(data=df, x='cut', y='price', showfliers=False, ax=axes[2])
axes[2].set_title('Распределение цены по качеству огранки')
axes[2].set_xlabel('cut')
axes[2].set_ylabel('price, USD')
axes[2].tick_params(axis='x', rotation=20)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig02_seaborn_relationships.png', dpi=220, bbox_inches='tight')
plt.close(fig)
df_py = df.copy()
df_py['carat_bin'] = pd.cut(df_py['carat'], bins=np.arange(0.2, 5.31, 0.25), include_lowest=True)
mean_price_by_carat = df_py.groupby('carat_bin', observed=False)['price'].mean().reset_index()
mean_price_by_carat['carat_mid'] = mean_price_by_carat['carat_bin'].apply(lambda x: x.mid)
median_depth_by_cut = df_py.groupby('cut', observed=False)['depth'].median().reindex(['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'])
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(mean_price_by_carat['carat_mid'], mean_price_by_carat['price'], marker='o')
axes[0].set_title('Средняя цена по интервалам carat')
axes[0].set_xlabel('Средина интервала carat')
axes[0].set_ylabel('Средняя цена, USD')
axes[0].grid(True, alpha=0.3)
axes[1].bar(median_depth_by_cut.index.astype(str), median_depth_by_cut.values)
axes[1].set_title('Медианная глубина depth по категориям cut')
axes[1].set_xlabel('cut')
axes[1].set_ylabel('Медиана depth, %')
axes[1].tick_params(axis='x', rotation=20)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig03_pyplot_features.png', dpi=220, bbox_inches='tight')
plt.close(fig)
fig, ax = plt.subplots(figsize=(12, 4))
missing_sample = df.sample(n=600, random_state=1).isna().astype(int)
sns.heatmap(missing_sample.T, cbar=True, cmap='Blues', ax=ax)
ax.set_title('Тепловая карта пропущенных значений (выборка 600 строк)')
ax.set_xlabel('Номер строки в выборке')
ax.set_ylabel('Признаки')
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig04_missing_values_heatmap.png', dpi=220, bbox_inches='tight')
plt.close(fig)
fig, ax = plt.subplots(figsize=(9, 7))
corr = df[numeric_cols].corr(numeric_only=True)
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0, square=True, ax=ax)
ax.set_title('Матрица корреляции числовых признаков')
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig05_correlation_heatmap.png', dpi=220, bbox_inches='tight')
plt.close(fig)
outlier_counts = {}
for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outlier_counts[col] = int(((df[col] < lower) | (df[col] > upper)).sum())
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.boxplot(data=df[numeric_cols], orient='h', ax=axes[0], showfliers=True)
axes[0].set_title('Диаграммы размаха числовых признаков')
axes[0].set_xlabel('Значение')
axes[1].bar(list(outlier_counts.keys()), list(outlier_counts.values()))
axes[1].set_title('Количество выбросов по IQR')
axes[1].set_ylabel('Количество')
axes[1].tick_params(axis='x', rotation=30)
for i, v in enumerate(outlier_counts.values()):
    axes[1].text(i, v, str(v), ha='center', va='bottom', fontsize=8)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig06_outliers_boxplots.png', dpi=220, bbox_inches='tight')
plt.close(fig)
filter1 = df[df['cut'].isin(['Ideal', 'Premium']) & df['color'].isin(['D', 'E', 'F'])]
filter2 = df[(df['carat'] >= 1.0) & (df['price'] <= 10000)]
filter3 = df[df['depth'].between(60, 63) & df['table'].between(54, 60)]
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].hist(filter1['price'], bins=35, edgecolor='black')
axes[0].set_title(f'Ф1: Ideal/Premium и цвет D-F\n(n={len(filter1)})')
axes[0].set_xlabel('price, USD')
axes[0].set_ylabel('Частота')
axes[1].scatter(filter2['carat'], filter2['price'], alpha=0.3, s=10)
axes[1].set_title(f'Ф2: carat ≥ 1 и price ≤ 10000\n(n={len(filter2)})')
axes[1].set_xlabel('carat')
axes[1].set_ylabel('price, USD')
filter3['cut'].value_counts().reindex(['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']).plot(kind='bar', ax=axes[2])
axes[2].set_title(f'Ф3: depth 60-63 и table 54-60\n(n={len(filter3)})')
axes[2].set_xlabel('cut')
axes[2].set_ylabel('Количество')
axes[2].tick_params(axis='x', rotation=20)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig07_filtering_results.png', dpi=220, bbox_inches='tight')
plt.close(fig)
rng = np.random.default_rng(42)
df_noise = df.copy()
df_noise['carat_noisy'] = np.clip(df_noise['carat'] + rng.normal(0, 0.015, size=len(df_noise)), 0, None)
df_noise['depth_noisy'] = df_noise['depth'] + rng.normal(0, 0.25, size=len(df_noise))
sample_noise = df_noise.sample(n=5000, random_state=7)
fig, axes = plt.subplots(2, 2, figsize=(12, 9))
axes[0, 0].hist(df_noise['carat'], bins=40, alpha=0.6, label='Исходный')
axes[0, 0].hist(df_noise['carat_noisy'], bins=40, alpha=0.6, label='С шумом')
axes[0, 0].set_title('Распределение carat')
axes[0, 0].legend()
axes[0, 1].scatter(sample_noise['carat'], sample_noise['carat_noisy'], alpha=0.3, s=10)
axes[0, 1].set_title('Исходный carat vs carat с шумом')
axes[0, 1].set_xlabel('carat')
axes[0, 1].set_ylabel('carat_noisy')
axes[1, 0].hist(df_noise['depth'], bins=40, alpha=0.6, label='Исходный')
axes[1, 0].hist(df_noise['depth_noisy'], bins=40, alpha=0.6, label='С шумом')
axes[1, 0].set_title('Распределение depth')
axes[1, 0].legend()
axes[1, 1].scatter(sample_noise['depth'], sample_noise['depth_noisy'], alpha=0.3, s=10)
axes[1, 1].set_title('Исходный depth vs depth с шумом')
axes[1, 1].set_xlabel('depth')
axes[1, 1].set_ylabel('depth_noisy')
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig08_noise_effect.png', dpi=220, bbox_inches='tight')
plt.close(fig)
df_cat = df.copy()
df_cat['price_category'] = pd.cut(df_cat['price'], bins=[0, 1000, 3000, 7000, 12000, np.inf], labels=['Очень низкая', 'Низкая', 'Средняя', 'Высокая', 'Премиум'])
df_cat['carat_category'] = pd.cut(df_cat['carat'], bins=[0, 0.5, 1.0, 1.5, 2.0, np.inf], labels=['До 0.5', '0.5-1.0', '1.0-1.5', '1.5-2.0', 'Более 2.0'])
df_cat['size_group'] = np.select([df_cat['x'] * df_cat['y'] * df_cat['z'] < 80, df_cat['x'] * df_cat['y'] * df_cat['z'] < 160], ['Малый', 'Средний'], default='Крупный')
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
df_cat['price_category'].value_counts().sort_index().plot(kind='bar', ax=axes[0])
axes[0].set_title('Категории цены')
axes[0].set_ylabel('Количество')
axes[0].tick_params(axis='x', rotation=30)
df_cat['carat_category'].value_counts().sort_index().plot(kind='bar', ax=axes[1])
axes[1].set_title('Категории массы carat')
axes[1].set_ylabel('Количество')
axes[1].tick_params(axis='x', rotation=30)
df_cat['size_group'].value_counts().reindex(['Малый', 'Средний', 'Крупный']).plot(kind='pie', autopct='%1.1f%%', ax=axes[2])
axes[2].set_ylabel('')
axes[2].set_title('Новая категория size_group')
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig09_numeric_to_categorical.png', dpi=220, bbox_inches='tight')
plt.close(fig)
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
for ax, col in zip(axes, cat_cols):
    df[col].value_counts().plot(kind='bar', ax=ax)
    ax.set_title(f'Распределение {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Количество')
    ax.tick_params(axis='x', rotation=30)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig10_categorical_distributions.png', dpi=220, bbox_inches='tight')
plt.close(fig)
df_encoded = df.copy()
encoder = LabelEncoder()
df_encoded['cut_encoded'] = encoder.fit_transform(df_encoded['cut'].astype(str))
agg = df_encoded.groupby('clarity', observed=False).agg(mean_price=('price', 'mean'), median_carat=('carat', 'median'), count=('price', 'size')).reset_index()
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
cut_counts = df_encoded['cut_encoded'].value_counts().sort_index()
axes[0].bar(cut_counts.index.astype(str), cut_counts.values)
axes[0].set_title('Label Encoding признака cut')
axes[0].set_xlabel('cut_encoded')
axes[0].set_ylabel('Количество')
axes[0].set_xticks(range(len(encoder.classes_)))
axes[0].set_xticklabels([f'{i}: {c}' for i, c in enumerate(encoder.classes_)], rotation=35, ha='right')
axes[1].bar(agg['clarity'].astype(str), agg['mean_price'])
axes[1].set_title('Средняя цена по категориям clarity')
axes[1].set_xlabel('clarity')
axes[1].set_ylabel('Средняя цена, USD')
axes[1].tick_params(axis='x', rotation=30)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig11_encoding_aggregation.png', dpi=220, bbox_inches='tight')
plt.close(fig)
df_clean = df.drop_duplicates().copy()
zero_mask = (df_clean[['x', 'y', 'z']] == 0).any(axis=1)
df_clean = df_clean[~zero_mask]
for col in ['price', 'carat', 'table']:
    q1 = df_clean[col].quantile(0.25)
    q3 = df_clean[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].hist(df['price'], bins=45, alpha=0.6, label='До')
axes[0].hist(df_clean['price'], bins=45, alpha=0.6, label='После')
axes[0].set_title('Распределение price до/после обработки')
axes[0].set_xlabel('price, USD')
axes[0].set_ylabel('Частота')
axes[0].legend()
volume_values = [len(df), len(df.drop_duplicates()), len(df_clean)]
axes[1].bar(['Исходный', 'Без дублей', 'После фильтрации'], volume_values)
axes[1].set_title('Изменение объема датасета')
axes[1].set_ylabel('Количество строк')
axes[1].tick_params(axis='x', rotation=20)
for i, v in enumerate(volume_values):
    axes[1].text(i, v, str(v), ha='center', va='bottom', fontsize=8)
before_zero = int((df[['x', 'y', 'z']] == 0).any(axis=1).sum())
after_zero = int((df_clean[['x', 'y', 'z']] == 0).any(axis=1).sum())
axes[2].bar(['До', 'После'], [before_zero, after_zero])
axes[2].set_title('Строки с нулевыми размерами x/y/z')
axes[2].set_ylabel('Количество')
for i, v in enumerate([before_zero, after_zero]):
    axes[2].text(i, v, str(v), ha='center', va='bottom', fontsize=8)
fig.tight_layout()
fig.savefig(OUT_DIR / 'fig12_changes_after_processing.png', dpi=220, bbox_inches='tight')
plt.close(fig)
